image: ruby

pages:
  stage: build
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build mkt-lab.gemspec
  artifacts:
    paths:
    - public
    - "mkt-lab-*.gem"
  only:
  - master
