# site settings
title: 市场学研究实验室
subtitle: (MKT-LAB)
email: mkt-lab@outlook.com
description: Official Website of MKT-LAB.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: China
phone: 

# social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:
weibo_url: https://weibo.com/u/7881548978

# build settings
markdown: kramdown

sass:
  style: compressed
