# netlify.toml
[build]
  # Specify the build command
  command = "gem install jekyll && jekyll build -d public && gem build mkt-lab.gemspec"
  # Define the directory that Netlify will publish
  publish = "_site"
  # Environment variables can be set here
  # environment = { ... }

# You can specify different contexts like deploy previews or branch deploys
# For example, for the master branch:
[context.master]
  # Master branch specific settings
